spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taobaozym?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
fdfs:
  tracker-list:
  - 192.168.85.11:22122
  connect-timeout: 600
  so-timeout: 1500